version: "3.9"
services:
  chop_1:
    container_name: chop_1
    build:
      context: flag_container
      dockerfile: Dockerfile
    ports:
      - "2022:22"
    networks:
      nw0:
    command: bash start_nc.sh
  chop_2:
    build:
      context: webserver
      dockerfile: Dockerfile
    container_name: chop_2
    networks:
      nw0:

networks:
  nw0:
    external: false
